services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 3000
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tune-ops-7zz7zz.rule=Host(`ops.shash7.com`)"
      - "traefik.http.routers.tune-ops-7zz7zz.entrypoints=websecure"
      - "traefik.http.routers.tune-ops-7zz7zz.tls.certResolver=letsencrypt"
      - "traefik.http.services.tune-ops-7zz7zz.loadbalancer.server.port=3000"
    volumes:
      - ./app:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      args:
        DATABASE_URL: mysql://root:12345678@mysql:3306/tune
    ports:
      - "2000:2000" # Expose backend on port 2000
    environment:
      - DATABASE_URL=mysql://root:12345678@mysql:3306/tune # MySQL connection string
      - APP_URL="http://localhost"
      - CORS=*
      - NODE_ENV=production
    depends_on:
      - mysql
    networks:
      - dokploy-network

  mysql:
    image: mysql:8.0
    command: >
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "tune"
      MYSQL_ROOT_PASSWORD: "12345678"
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysql
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
