services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    networks:
      - app-network
    volumes:
      - ./app:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      args:
        DATABASE_URL: mysql://root:12345678@mysql:3306/tune
    ports:
      - "2000:2000" # Expose backend on port 2000
    environment:
      - DATABASE_URL=mysql://root:12345678@mysql:3306/tune # MySQL connection string
      - APP_URL="http://localhost"
      - CORS=*
      - NODE_ENV=production
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    command: >
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "tune"
      MYSQL_ROOT_PASSWORD: "12345678"
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
