services:
  app:
    build:
      context: ./app
    ports:
      - "80:80" # Expose Vue app on port 80
    env_file:
      - .env # Reference to the .env file in the root if needed
    networks:
      - app-network
    volumes:
      - ./app:/app
      - /app/node_modules
    command: ["nginx", "-g", "daemon off;"]

  backend:
    build:
      context: ./backend
    ports:
      - "2000:2000" # Expose backend on port 2000
    env_file:
      - .env # Reference to the .env file in the root if needed
    environment:
      - DATABASE_URL=mysql://root:12345678@mysql:3306/tune # MySQL connection string
      - APP_URL="http://localhost"
      - CORS=*
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    command: >
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "tune"
      MYSQL_ROOT_PASSWORD: "12345678"
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
