services:
  # Backend Node.js service
  - type: web
    name: tune-backend
    plan: free
    runtime: node
    rootDir: backend
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/tune
      - key: API_URL
        value: https://api.tune
      - key: APP_URL
        value: https://app.tune
      - key: PORT
        value: 8080
      - key: SECRET
        generateValue: true
      - key: EVENT_STORE
        value: mysql

  # MySQL Service
  - type: pserv
    name: mysql
    plan: starter
    runtime: docker
    image: mysql:8.0
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_DATABASE
        value: tune
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true

  # Frontend static SPA
  - type: web
    name: tune-frontend
    runtime: static
    rootDir: app
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

envVarGroups:
  - name: tune-settings
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
