version: "3.8"

services:
  mysql:
    image: mysql:8.2
    container_name: tune-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tune_root_password
      MYSQL_DATABASE: tune
      MYSQL_USER: tune_user
      MYSQL_PASSWORD: tune_password
    ports:
      - "3307:3306" # host:container
    volumes:
      - mysql-data:/var/lib/mysql

  tune:
    image: ghcr.io/tune-co/tune:0.1.7
    container_name: tune-app
    depends_on:
      - mysql
    restart: always
    ports:
      - "3000:80" # For frontend (nginx serving the Vue SPA)
      - "4337:4337" # For backend API
    environment:
      DATABASE_URL: mysql://tune_user:tune_password@mysql:3306/tune
      APP_URL: http://localhost:3000
      VAPID_EMAIL: ""
      VAPID_PUBLIC_KEY: ""
      VAPID_PRIVATE_KEY: ""
      PORT: ""
      SECRET: ""
      REMOVE_TEST_EVENTS_AT: ""
      CORS: "*"
      RESEND: ""
      ADMIN_EMAIL: admin@email.com
      SMTP_HOST: ""
      SMTP_PORT: ""
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""

volumes:
  mysql-data:
